import 'package:gains/models/workout_models.dart';

// Varsayılan egzersiz listesi
final List<Map<String, dynamic>> defaultExercises = [
  {
    'name': 'Bench Press (Barbell)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 4,
    'targetReps': 10,
  },
  {
    'name': 'Bench Press (Dumbbell)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 4,
    'targetReps': 10,
  },
  {
    'name': 'Incline Bench Press (Barbell)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Incline Bench Press (Dumbbell)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Decline Bench Press',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Chest Flyes (Dumbbell)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Chest Flyes (Machine/Pec Deck)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Push Ups',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 20,
  },
  {
    'name': 'Cable Crossover (High to Low)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Cable Crossover (Low to High)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Dips (Chest Focus)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Chest Press Machine',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Smith Machine Bench Press',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 4,
    'targetReps': 10,
  },
  {
    'name': 'Pullover (Dumbbell)',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Landmine Press',
    'muscleGroup': MuscleGroup.chest.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Pull Ups',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Chin Ups',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Lat Pulldown (Wide Grip)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 4,
    'targetReps': 12,
  },
  {
    'name': 'Lat Pulldown (Close Grip/V-Bar)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 4,
    'targetReps': 12,
  },
  {
    'name': 'Lat Pulldown (Reverse Grip)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 4,
    'targetReps': 12,
  },
  {
    'name': 'Barbell Row',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 4,
    'targetReps': 8,
  },
  {
    'name': 'Dumbbell Row (Single Arm)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Seated Cable Row',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'T-Bar Row',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Deadlift (Conventional)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 5,
  },
  {
    'name': 'Deadlift (Sumo)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 5,
  },
  {
    'name': 'Rack Pulls',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 8,
  },
  {
    'name': 'Face Pulls',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Straight Arm Pulldown',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Back Hyperextensions',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Shrugs (Barbell)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Shrugs (Dumbbell)',
    'muscleGroup': MuscleGroup.back.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Squat (Barbell Back)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 4,
    'targetReps': 8,
  },
  {
    'name': 'Squat (Check Front)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Goblet Squat',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Leg Press',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Hack Squat',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Lunges (Walking)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Bulgarian Split Squat',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Romanian Deadlift (RDL)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 4,
    'targetReps': 10,
  },
  {
    'name': 'Stiff Leg Deadlift',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Leg Extension',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Leg Curl (Seated)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Leg Curl (Lying)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Hip Thrust',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 4,
    'targetReps': 12,
  },
  {
    'name': 'Glute Bridge',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Calf Raises (Standing)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 4,
    'targetReps': 20,
  },
  {
    'name': 'Calf Raises (Seated)',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 4,
    'targetReps': 15,
  },
  {
    'name': 'Hip Adduction Machine',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Hip Abduction Machine',
    'muscleGroup': MuscleGroup.legs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Overhead Press (Barbell)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 4,
    'targetReps': 8,
  },
  {
    'name': 'Overhead Press (Dumbbell)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Shoulder Press Machine',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Lateral Raises (Dumbbell)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 4,
    'targetReps': 15,
  },
  {
    'name': 'Lateral Raises (Cable)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Front Raises (Dumbbell)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Front Raises (Plate)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Arnold Press',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Rear Delt Flyes (Dumbbell)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Rear Delt Flyes (Machine)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Upright Row (Barbell/EZ Bar)',
    'muscleGroup': MuscleGroup.shoulders.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Barbell Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'EZ Bar Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Dumbbell Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Hammer Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Incline Dumbbell Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Preacher Curl (Machine/Free)',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Concentration Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Cable Bicep Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Reverse Curl',
    'muscleGroup': MuscleGroup.biceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Triceps Pushdown (Cable)',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Triceps Pushdown (Rope)',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Skull Crushers',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Overhead Triceps Extension (Dumbbell)',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Overhead Triceps Extension (Cable)',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Close Grip Bench Press',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 10,
  },
  {
    'name': 'Dips (Triceps/Bench)',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Tricep Kickbacks',
    'muscleGroup': MuscleGroup.triceps.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Plank',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 60,
  },
  {
    'name': 'Crunches',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 20,
  },
  {
    'name': 'Leg Raises (Hanging)',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Leg Raises (Lying)',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
  {
    'name': 'Bicycle Crunches',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 20,
  },
  {
    'name': 'Russian Twist',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 20,
  },
  {
    'name': 'Ab Wheel Rollout',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 12,
  },
  {
    'name': 'Cable Woodchoppers',
    'muscleGroup': MuscleGroup.abs.name,
    'targetSets': 3,
    'targetReps': 15,
  },
];
